
- hosts: [service/haproxy]
  sudo: yes
  tasks:
    - file: state=directory path=/etc/solar/{{name}}
      # TODO Remove hardcoded path
    - template: src=/vagrant/examples/resources/templates/haproxy.cfg.j2 dest=/etc/solar/{{name}}/haproxy.cfg backup=yes
    - shell: docker run -d \
        --net="host" \
        --privileged \
        -v /etc/solar/{{name}}/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro \
        --name {{name}} {{image}}
