id: haproxy_keystone_config
handler: none
version: 1.0.0
input:
    name:
      schema: str!
      value: keystone-admin
    listen_port:
      schema: int!
      value: 9999
    ports:
      schema: [int]
      value:
    servers:
      schema: [str]
      value:

tags: [resources/haproxy, resource/haproxy_keystone_config]
