id: riak_commit
handler: ansible
version: 1.0.0
actions:
  commit: actions/commit.yml
input:
    ip:
      schema: str!
      value:
    ssh_key:
      schema: str!
      value:
    ssh_user:
      schema: str!
      value:
    riak_names:
      schema: [{riak_name: str}]
      value: []
