handler: puppet
id: 'neutron_plugins_ovs_puppet'
input:
  ip:
    schema: str!
    value: ''
  ssh_key:
    schema: str!
    value: ''
  ssh_user:
    schema: str!
    value: ''

  package_ensure:
    schema: str
    value: 'present'
  sql_connection:
    schema: str
    value: ''
  sql_max_retries:
    schema: str
    value: ''
  sql_idle_timeout:
    schema: str
    value: ''
  reconnect_interval:
    schema: str
    value: ''
  tenant_network_type:
    schema: str
    value: 'vlan'
  network_vlan_ranges:
    schema: str
    value: ''
  tunnel_id_ranges:
    schema: str
    value: '1:1000'
  vxlan_udp_port:
    schema: int
    value: 4789

  git:
    schema: {repository: str!, branch: str!}
    value: {repository: 'https://github.com/openstack/puppet-neutron', branch: '5.1.0'}

puppet_module: 'neutron'
tags: [resource/neutron, resource/neutron_plugins_ovs]
version: 1.0.0
