
- hosts: [service/mariadb]
  sudo: yes
  tasks:
    - shell: docker run \
        -d \
        --net="host" \
        --privileged \
        --name {{name}} \
        -e "MARIADB_ROOT_PASSWORD={{root_password}}" \
        -e "BIND_ADDRESS={{bind_ip}}" \
        {{image}}
