id: mariadb
handler: ansible
version: 1.0.0
input:
    image: 
      schema: str!
      value: mariadb
    root_password:
      schema: str!
      value: password
    port:
      schema: int!
      value: 3306
    ip:
      schema: str!
      value:
    ssh_key:
      schema: str!
      value:
    ssh_user:
      schema: str!
      value:

tags: [resource/mariadb, resources/mariadb]
