id: ssh_key
handler: ansible_playbook
version: 1.0.0
actions:
input:
    ip:
      schema: str!
      value:
    ssh_key:
      schema: str!
      value:
    ssh_user:
      schema: str!
      value:
    path:
      schema: str!
      value:
    pub_path:
      schema: str!
      value:
    passphrase:
      schema: str
      value: default_passphrase
