id: puppet_inifile
handler: puppet
puppet_module: inifile
version: 1.0.0
input:
    ip:
      schema: str!
      value:
    ssh_key:
      schema: str!
      value:
    ssh_user:
      schema: str!
      value:

tags: [resource/keystone_service, resources/keystone]
