id: haproxy_config
handler: ansible
version: 1.0.0
input:
    ip:
      schema: str!
      value:
    config_dir:
      schema: {src: str!, dst: str!}
      value: {src: /etc/solar/haproxy, dst: /etc/haproxy}
    listen_ports:
      schema: [{value: int}]
      value: []
    configs:
      schema: [{value: [{value: str}]}]
      value: []
    configs_names:
      schema: [{value: str}]
      value: []
    configs_ports:
      schema: [{value: [{value: int}]}]
      value: []
    configs_protocols:
      schema: [{value: str}]
      value: []
    ssh_user:
      schema: str!
      value:
    ssh_key:
      schema: str!
      value:

tags: [resources/haproxy, resource/haproxy_config]
