- hosts: [{{host}}]]
  sudo: yes
  tasks:
    - new_rabbitmq_user: user={{user_name}}
                         password={{password}}
                         vhost={{vhost_name}}
                         configure_priv=.*
                         read_priv=.*
                         write_priv=.*
                         state=present
