id: rabbitmq_service
handler: ansible
version: 1.0.0
input:
    image: 
      schema: str!
      value: rabbitmq:3-management
    container_name:
      schema: str!
      value: rabbitmq_service
    management_port:
      schema: str!
      value: 15672
    port:
      schema: str!
      value: 5672
    ip:
      schema: str!
      value:
    ssh_key:
      schema: str!
      value:
    ssh_user:
      schema: str!
      value:

tags: [resources/rabbitmq, resource/rabbitmq_service]
