id: container
handler: ansible
version: 1.0.0
input:
    ip:
      schema: str!
      value:
    image:
      schema: str!
      value:
    ports:
      schema: [int]
      value: []
    host_binds:
      schema: [int]
      value: []
    volume_binds:
      schema: [int]
      value: []
    ssh_user:
      schema: str!
      value: []
    ssh_key:
      schema: str!
      value: []
