id: nova
handler: puppet
puppet_module: nova
version: 1.0.0
input:
    db_user:
      schema: str!
      value: nova
    db_password:
      schema: str!
      value:
    db_name:
      schema: str!
      value:
    db_host:
      schema: str!
      value:

    rabbitmq_user:
      schema: str!
      value:
    rabbitmq_password:
      schema: str!
      value:
    rabbitmq_host:
      schema: str!
      value:

    keystone_password:
      schema: str!
      value: 
    keystone_port:
      schema: int!
      value:
    keystone_host:
      schema: str!
      value:
    keystone_tenant_name:
      schema: str!
      value:
    keystone_user_name:
      schema: str!
      value:

    git:
      schema: {repository: str!, branch: str!}
      value: {repository: 'https://github.com/openstack/puppet-nova', branch: 'stable/juno'}

    ip:
      schema: str!
      value:
    ssh_key:
      schema: str!
      value:
    ssh_user:
      schema: str!
      value:

tags: [resource/nova_service, resources/nova]
