handler: puppet
id: 'neutron_agents_ovs_puppet'
input:
  ip:
    schema: str!
    value:
  ssh_key:
    schema: str!
    value:
  ssh_user:
    schema: str!
    value:

  package_ensure:
    schema: str
    value: 'present'
  bridge_uplinks:
    schema: [str]
    value: []
  bridge_mappings:
    schema: [str]
    value: []
  integration_bridge:
    schema: str
    value: 'br-int'
  enable_tunneling:
    schema: bool
    value: false
  tunnel_types:
    schema: [str]
    value: []
  local_ip:
    schema: str
    value: 
  tunnel_bridge:
    schema: str
    value: 'br-tun'
  vxlan_udp_port:
    schema: int
    value: 4789
  polling_interval:
    schema: int
    value: 2
  firewall_driver:
    schema: str
    value: 'neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver'
  veth_mtu:
    schema: str
    value: 

  git:
    schema: {repository: str!, branch: str!}
    value: {repository: 'https://github.com/openstack/puppet-neutron', branch: '5.1.0'}

puppet_module: 'neutron'
tags: [resource/neutron, resource/neutron_agents_ovs]
version: 1.0.0
