id: keystone_service_endpoint
handler: ansible
version: 1.0.0
input:
    keystone_host:
      schema: str!
      value:
    keystone_admin_port:
      schema: int!
      value:
    admin_token:
      schema: str!
      value:
    type:
      schema: str!
    description:
      schema: str!
    name:
      schema: str!
    public_ip:
      schema: str!
    public_port:
      schema: int!
    publicurl:
      schema: str!
      value: http://{{public_ip}}:{{public_port}}/v2.0
    internal_ip:
      schema: str!
    internal_port:
      schema: int!
    internalurl:
      schema: str!
      value: http://{{ip}}:{{port}}/v2.0
    admin_ip:
      schema: str!
    admin_port:
      schema: int!
    adminurl:
      schema: str!
      value: http://{{ip}}:{{admin_port}}/v2.0
    ip:
      schema: str!
      value:
    ssh_key:
      schema: str!
      value:
    ssh_user:
      schema: str!
      value:

tags: [resource/keystone_service_endpoint, resources/keystone]
