id: keystone_user
handler: ansible
version: 1.0.0
input:
    keystone_host:
      schema: str!
      value:
    keystone_port:
      schema: int!
      value:
    admin_token:
      schema: str!
      value:
    port:
      schema: int!
      value:
    admin_port:
      schema: int!
      value:
    name:
      schema: str!
      value:
    type:
      schema: str!
      value:
    description:
      schema: str!
      value:
    publicurl:
      schema: str!
      value:
    internalurl:
      schema: str!
      value:
    adminurl:
      schema: str!
      value:
    ip:
      schema: str!
      value:
    ssh_key:
      schema: str!
      value:
    ssh_user:
      schema: str!
      value:

tags: [resource/keystone_tenant, resources/keystone]

