id: lxc_container
handler: ansible_playbook
version: 1.0.0
actions:
input:
    ip:
      schema: str!
      value:
    ssh_key:
      schema: str!
      value:
    ssh_user:
      schema: str!
      value:
    ansible_ssh_host:
      schema: str!
      value:
    container_address:
      schema: str!
      value:
    container_name:
      schema: str!
      value:
    roles:
      schema: [{value: str}]
      value:
        - https://github.com/stackforge/os-ansible-deployment/trunk/playbooks/roles/lxc_container_create
        - https://github.com/stackforge/os-ansible-deployment/trunk/playbooks/roles/lxc_container_destroy
