input:
  key:
    schema: str
    value:
  password:
    schema: str
    value:
  user:
    schema: str!
    value:
  port:
    schema: int!
    value: 22
  name:
    schema: str!
    value: ssh
  location_id:
    schema: str
    value:
    reverse: True
    is_own: False
  transports_id:
    schema: str
    value:
    is_emit: False
