id: glance_puppet
handler: puppet
puppet_module: glance
version: 1.0.0
input:
    db_host:
      schema: str!
      value:
    db_port:
      schema: int!
      value:
    db_user:
      schema: str!
      value: keystone
    db_password:
      schema: str!
      value: keystone
    db_name:
      schema: str!
      value: keystone

    keystone_host:
      schema: str!
      value:
    keystone_port:
      schema: int!
      value: 5000
    keystone_user:
      schema: str!
      value: glance
    keystone_role:
      schema: str!
      value: glance
    keystone_password:
      schema: str!
      value: glance123
    keystone_tenant:
      schema: str!
      value: services

    git:
      schema: {repository: str!, branch: str!}
      value: {repository: 'https://github.com/openstack/puppet-glance', branch: 'stable/juno'}

    ip:
      schema: str!
      value:
    ssh_key:
      schema: str!
      value:
    ssh_user:
      schema: str!
      value:

tags: [resource/glance_service, resources/glance]
