id: keystone_config
handler: ansible
version: 1.0.0
input:
    config_dir:
      schema: str!
      value:
    admin_token:
      schema: str!
      value:
    db_user:
      schema: str!
      value:
    db_password:
      schema: str!
      value:
    db_host:
      schema: str!
      value:
    db_name:
      schema: str!
      value:
    ip:
      schema: str!
      value:
    ssh_key:
      schema: str!
      value:
    ssh_user:
      schema: str!
      value:
