id: riak_node
handler: ansible
version: 1.0.0
actions:
  commit: actions/commit.yml
  run: actions/run.yml
  join: actions/join.yml
input:
    ip:
      schema: str!
      value:
    ssh_key:
      schema: str!
      value:
    ssh_user:
      schema: str!
      value:
    riak_name:
      schema: str!
      value:
    join_to:
      schema: str
      value:
