id: haproxy_general_config
handler: none
version: 1.0.0
input:
    name:
      schema: str!
      value: general_haproxy
    listen_port:
      schema: int!
      value: 9999
    protocol:
      schema: str!
      value: http
    ports:
      schema: [{value: int}]
      value: []
    servers:
      schema: [{value: str}]
      value: []

tags: [resources/haproxy, resource/haproxy_general_config]
