id: mariadb_keystone_db
handler: ansible
version: 1.0.0
actions:
    run: run.yml
    remove: remove.yml
input:
    db_name:
      schema: str!
      value: keystone_db
    login_user:
      schema: str!
      value: root
    login_password:
      schema: str!
      value:
    login_port:
      schema: int!
      value:
    ip:
      schema: str!
      value:
    ssh_key:
      schema: str!
      value:
    ssh_user:
      schema: str!
      value:

tags: [resource/mariadb_keystone_db, resources/mariadb]
